//! Conformance against the semantic-digest contract goldens.
//!
//! `tests/fixtures/goldens.json` is generated by the Python reference (`tests/reference/`), which is
//! the contract's canonicalizer + set-normalizer. Its digests are the **un-profiled** content_id of
//! the set-normalized record — the contract's current (pre-profile-adoption) digest. This crate must
//! reproduce every one of them from the value bytes alone, which is the Rust/Python parity proof over
//! the goldens' value domain (ASCII strings + integers); over exactly that domain full RFC 8785
//! (`serde_jcs`) and the Python `json.dumps(sort_keys=...)` reference are byte-identical.
//!
//! The profile-bound digest ([`assay_canonical::semantic_digest`]) deliberately moves the digest by
//! binding the `canonicalization_profile` into the preimage (the contract's "old/new golden pair" on
//! adoption); it is exercised in the crate's `profile` unit tests, not here, because these goldens
//! pin the pre-profile bytes.

use assay_canonical::{content_id, set_paths::normalize_sets};
use serde_json::Value;

#[derive(serde::Deserialize)]
struct Golden {
    id: String,
    class: String,
    set_paths: Vec<Vec<String>>,
    record: Value,
    reordered: Value,
    new_digest: String,
    reordered_new_digest: String,
}

fn load_goldens() -> Vec<Golden> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/goldens.json");
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    serde_json::from_str(&raw).expect("parse goldens.json")
}

/// The un-profiled digest the goldens pin: normalize the registered set-paths, then content-address.
fn unprofiled_digest(record: &Value, set_paths: &[Vec<String>]) -> String {
    let normalized = normalize_sets(record, set_paths).expect("golden records are well-formed");
    content_id(&normalized).expect("content_id")
}

#[test]
fn reproduces_every_golden_digest() {
    let goldens = load_goldens();
    assert!(!goldens.is_empty(), "no goldens loaded");
    for g in &goldens {
        assert_eq!(
            unprofiled_digest(&g.record, &g.set_paths),
            g.new_digest,
            "new_digest mismatch for {}",
            g.id
        );
        assert_eq!(
            unprofiled_digest(&g.reordered, &g.set_paths),
            g.reordered_new_digest,
            "reordered_new_digest mismatch for {}",
            g.id
        );
    }
}

#[test]
fn set_classes_collapse_ordered_classes_do_not() {
    let mut sets_seen = 0;
    let mut ordered_seen = 0;
    for g in &load_goldens() {
        let a = unprofiled_digest(&g.record, &g.set_paths);
        let b = unprofiled_digest(&g.reordered, &g.set_paths);
        match g.class.as_str() {
            "set" | "already_canonical_set" => {
                assert_eq!(a, b, "a set must collapse under reorder: {}", g.id);
                sets_seen += 1;
            }
            "ordered" => {
                assert_ne!(a, b, "an ordered field must stay order-sensitive: {}", g.id);
                ordered_seen += 1;
            }
            other => panic!("unknown class {other:?} in {}", g.id),
        }
    }
    // Non-vacuity: both directions of the contract are actually exercised.
    assert!(sets_seen > 0, "no set-class goldens exercised");
    assert!(ordered_seen > 0, "no ordered-class goldens exercised");
}
