pub const CI_EVAL_YAML: &str = r#"version: 1
suite: "ci_smoke"
model: "trace"
tests:
  - id: "ci_smoke_regex"
    input:
      prompt: "ci_regex"
    expected:
      type: regex_match
      pattern: "Hello\\s+CI"
      flags: ["i"]
  - id: "ci_smoke_schema"
    input:
      prompt: "ci_schema"
    expected:
      type: json_schema
      json_schema: "{}"
      schema_file: "schemas/ci_answer.schema.json"
  - id: "ci_smoke_semantic"
    input:
      prompt: "ci_semantic"
    expected:
      type: semantic_similarity_to
      text: "Hello Semantic"
      threshold: 0.99
"#;

pub const CI_SCHEMA_JSON: &str = r#"{
  "type": "object",
  "required": ["answer"],
  "properties": {
    "answer": { "type": "string" }
  },
  "additionalProperties": false
}"#;

pub const CI_TRACES_JSONL: &str = r#"{"schema_version": 1, "type": "assay.trace", "request_id": "ci_1", "prompt": "ci_regex", "response": "hello   ci", "model": "trace", "provider": "trace"}
{"schema_version": 1, "type": "assay.trace", "request_id": "ci_2", "prompt": "ci_schema", "response": "{\"answer\":\"ok\"}", "model": "trace", "provider": "trace"}
{"schema_version": 1, "type": "assay.trace", "request_id": "ci_3", "prompt": "ci_semantic", "response": "Hello Semantic", "model": "trace", "provider": "trace", "meta": {"assay": {"embeddings": {"model":"trace-embed","response":[1.0,0.0,0.0],"reference":[1.0,0.0,0.0],"source_response":"trace","source_reference":"trace"}}}}
"#;

/// Blessed CI workflow template (v2)
/// Generated by `assay init --ci` and `assay init-ci --provider github`
/// See: https://github.com/Rul1an/assay/tree/main/assay-action
pub const CI_WORKFLOW_YML: &str = r#"name: Assay Gate
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  security-events: write  # Required for SARIF upload

jobs:
  assay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Assay Gate
        uses: Rul1an/assay/assay-action@v2
        with:
          config: ci-eval.yaml
          trace_file: traces/ci.jsonl
          # Output formats (all enabled by default in v2)
          # junit: true
          # sarif: true
          # summary: true

      # JUnit test annotations (failures shown in PR)
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Assay Tests
          path: .assay/reports/junit.xml
          reporter: java-junit
          fail-on-error: false

      # SARIF upload to GitHub Security tab
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: .assay/reports/sarif.json
          category: assay
"#;

pub const GITIGNORE: &str = "/.eval/\n/out/\n*.db\n*.db-shm\n*.db-wal\n/assay\n";

pub const ASSAY_CONFIG_DEFAULT_YAML: &str = r#"version: 2
policy: "policy.yaml"
baseline: ".assay/baseline.json"
"#;
