#!/usr/bin/env python3
"""Pin generate-agent-golden-path.py --check to compare, not write (#2372)."""

from __future__ import annotations

from pathlib import Path
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[2]
GENERATOR = Path("scripts/docs/generate-agent-golden-path.py")
STAGING = ROOT / "scripts/ci/lib/golden-path-fixture-staging.sh"
CONTRACT = Path("docs/generated/agent-golden-path.json")
GUIDE = Path("docs/guides/agent-golden-path.md")
CODEX_SKILL = Path(".agents/skills/assay-golden-path/SKILL.md")
UNKNOWN_ARGUMENT = "--not-a-real-flag"


def fail(message: str) -> None:
    raise SystemExit(message)


def seed_case(destination: Path) -> None:
    script = f"""
set -euo pipefail
# shellcheck source=scripts/ci/lib/golden-path-fixture-staging.sh
source {STAGING.as_posix()!r}
stage_golden_path_fixtures {destination.as_posix()!r} {ROOT.as_posix()!r}
mkdir -p {destination.as_posix()!r}/docs/guides
cp { (ROOT / GUIDE).as_posix()!r } { (destination / GUIDE).as_posix()!r }
"""
    completed = subprocess.run(["bash", "-c", script], check=False, capture_output=True, text=True)
    if completed.returncode != 0:
        fail("could not stage golden-path generator fixtures: " + completed.stderr.strip())


def snapshot_tree(root: Path) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        files[path.relative_to(root).as_posix()] = path.read_bytes()
    return files


def run_generator(root: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(GENERATOR), *args],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
    )


def plant_drift(root: Path, relative: Path, marker: str) -> None:
    path = root / relative
    path.write_bytes(path.read_bytes() + marker.encode("ascii"))


def combined_output(result: subprocess.CompletedProcess[str]) -> str:
    return result.stdout + result.stderr


def check_detects_named_drift_without_writing(root: Path) -> None:
    before = snapshot_tree(root)
    plant_drift(root, CONTRACT, "\n# contract-drift\n")
    plant_drift(root, CODEX_SKILL, "\n# skill-drift\n")
    drifted = snapshot_tree(root)
    result = run_generator(root, ["--check"])
    after = snapshot_tree(root)
    output = combined_output(result)
    if result.returncode == 0:
        fail("--check accepted drifted golden-path outputs")
    if after != drifted:
        fail("--check modified the tree it was asked only to compare")
    if before == after:
        fail("drift fixture did not change any generated bytes")
    for relative in (CONTRACT, CODEX_SKILL):
        if relative.as_posix() not in output:
            fail(f"--check did not name drifted path: {relative.as_posix()}")


def check_in_sync_is_clean(root: Path) -> None:
    before = snapshot_tree(root)
    result = run_generator(root, ["--check"])
    after = snapshot_tree(root)
    if result.returncode != 0:
        fail("--check rejected in-sync golden-path outputs: " + combined_output(result))
    if after != before:
        fail("--check modified an in-sync tree")


def check_rejects_unknown_argument(root: Path) -> None:
    before = snapshot_tree(root)
    result = run_generator(root, [UNKNOWN_ARGUMENT])
    after = snapshot_tree(root)
    if result.returncode == 0:
        fail("unknown generator argument was accepted")
    if after != before:
        fail("unknown generator argument modified the tree")


def apply_silent_repair_mutation(root: Path) -> None:
    path = root / GENERATOR
    text = path.read_text(encoding="utf-8")
    anchor = 'if __name__ == "__main__":\n    main()'
    if text.count(anchor) != 1:
        fail("silent-repair mutation could not find the generator entrypoint")
    path.write_text(
        text.replace(
            anchor,
            'if __name__ == "__main__":\n'
            "    import sys as _sys\n"
            "    _sys.argv = [_sys.argv[0]]\n"
            "    main()",
            1,
        ),
        encoding="utf-8",
    )


def expect_pins_reject(name: str, mutate) -> None:
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        mutate(root)
        try:
            check_detects_named_drift_without_writing(root)
        except SystemExit as error:
            if str(error) in {
                "--check accepted drifted golden-path outputs",
                "--check modified the tree it was asked only to compare",
            }:
                return
            raise
        fail(f"{name}: self-test accepted writer-mode --check")


def expect_unknown_pin_rejects(name: str, mutate) -> None:
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        mutate(root)
        try:
            check_rejects_unknown_argument(root)
        except SystemExit as error:
            if str(error) == "unknown generator argument was accepted":
                return
            raise
        fail(f"{name}: self-test accepted an ignored unknown argument")


def main() -> None:
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        check_in_sync_is_clean(root)
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        check_detects_named_drift_without_writing(root)
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        check_rejects_unknown_argument(root)

    expect_pins_reject("silent-repair --check", apply_silent_repair_mutation)
    expect_unknown_pin_rejects("ignored unknown argument", apply_silent_repair_mutation)
    print("golden-path generator --check: compares bytes, names drift, rejects unknown argv")


if __name__ == "__main__":
    main()
