#!/usr/bin/env python3
"""Pin generate-agent-golden-path.py --check to compare, not write (#2372)."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[2]
GENERATOR = Path("scripts/docs/generate-agent-golden-path.py")
STAGING = ROOT / "scripts/ci/lib/golden-path-fixture-staging.sh"
GUIDE = Path("docs/guides/agent-golden-path.md")
GUIDE_TABLE_START = "<!-- agent-golden-path-table:start -->"
UNKNOWN_ARGUMENT = "--not-a-real-flag"
PORTABLE_SCHEMA = Path("packaging/agent-plugin/schemas/plugin.schema.json")
PORTABLE_SCHEMA_LOCK = Path("packaging/agent-plugin/schemas/plugin.schema.lock.json")
PORTABLE_SCHEMA_URL = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"
PORTABLE_SCHEMA_SHA256 = "0a4aad95ce337878ad38802ebf0daa3fde76abe3f65400c86bcbb1ec0b3ab883"
# Closed public inventory. Do not build this from rendered_outputs().
GENERATED_OUTPUTS = (
    Path("docs/generated/agent-golden-path.json"),
    GUIDE,
    Path(".agents/skills/assay-golden-path/SKILL.md"),
    Path(".claude/skills/assay-golden-path/SKILL.md"),
    Path("packaging/claude-plugin/skills/assay-golden-path/SKILL.md"),
    Path(
        "packaging/claude-plugin/skills/assay-golden-path/references/agent-golden-path.json"
    ),
    Path(
        "packaging/claude-plugin/skills/assay-golden-path/assets/"
        "privileged-action-gate/mock_github_mcp.py"
    ),
    Path(
        "packaging/claude-plugin/skills/assay-golden-path/assets/"
        "privileged-action-gate/baseline-approved.json"
    ),
    Path(
        "packaging/claude-plugin/skills/assay-golden-path/assets/"
        "privileged-action-gate/policies/no-allowance.yaml"
    ),
    Path("packaging/agent-plugin/plugin.json"),
    Path("packaging/agent-plugin/skills/assay-golden-path/SKILL.md"),
    Path(
        "packaging/agent-plugin/skills/assay-golden-path/references/agent-golden-path.json"
    ),
    Path(
        "packaging/agent-plugin/skills/assay-golden-path/assets/"
        "privileged-action-gate/mock_github_mcp.py"
    ),
    Path(
        "packaging/agent-plugin/skills/assay-golden-path/assets/"
        "privileged-action-gate/baseline-approved.json"
    ),
    Path(
        "packaging/agent-plugin/skills/assay-golden-path/assets/"
        "privileged-action-gate/policies/no-allowance.yaml"
    ),
)


def fail(message: str) -> None:
    raise SystemExit(message)


def seed_case(destination: Path) -> None:
    script = f"""
set -euo pipefail
# shellcheck source=scripts/ci/lib/golden-path-fixture-staging.sh
source {STAGING.as_posix()!r}
stage_golden_path_fixtures {destination.as_posix()!r} {ROOT.as_posix()!r}
mkdir -p {destination.as_posix()!r}/docs/guides
cp { (ROOT / GUIDE).as_posix()!r } { (destination / GUIDE).as_posix()!r }
"""
    completed = subprocess.run(["bash", "-c", script], check=False, capture_output=True, text=True)
    if completed.returncode != 0:
        fail("could not stage golden-path generator fixtures: " + completed.stderr.strip())


def snapshot_tree(root: Path) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        files[path.relative_to(root).as_posix()] = path.read_bytes()
    return files


def run_generator(root: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(GENERATOR), *args],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
    )


def plant_drift(root: Path, relative: Path, marker: str) -> None:
    path = root / relative
    payload = path.read_bytes()
    encoded = marker.encode("ascii")
    if relative == GUIDE:
        anchor = GUIDE_TABLE_START.encode("ascii")
        if payload.count(anchor) != 1:
            fail("guide drift fixture lost the table start marker")
        payload = payload.replace(anchor, anchor + b"\n" + encoded, 1)
    else:
        payload = payload + encoded
    path.write_bytes(payload)


def combined_output(result: subprocess.CompletedProcess[str]) -> str:
    return result.stdout + result.stderr


def check_detects_named_drift_without_writing(root: Path) -> None:
    before = snapshot_tree(root)
    for relative in GENERATED_OUTPUTS:
        plant_drift(root, relative, f"\n# drift:{relative.as_posix()}\n")
    drifted = snapshot_tree(root)
    result = run_generator(root, ["--check"])
    after = snapshot_tree(root)
    output = combined_output(result)
    if result.returncode == 0:
        fail("--check accepted drifted golden-path outputs")
    if after != drifted:
        fail("--check modified the tree it was asked only to compare")
    if before == after:
        fail("drift fixture did not change any generated bytes")
    for relative in GENERATED_OUTPUTS:
        if relative.as_posix() not in output:
            fail(f"--check did not name drifted path: {relative.as_posix()}")


def check_in_sync_is_clean(root: Path) -> None:
    before = snapshot_tree(root)
    result = run_generator(root, ["--check"])
    after = snapshot_tree(root)
    if result.returncode != 0:
        fail("--check rejected in-sync golden-path outputs: " + combined_output(result))
    if after != before:
        fail("--check modified an in-sync tree")


def check_portable_schema_lock(root: Path) -> None:
    schema = (root / PORTABLE_SCHEMA).read_bytes()
    lock = json.loads((root / PORTABLE_SCHEMA_LOCK).read_text(encoding="utf-8"))
    expected = {
        "canonical_url": PORTABLE_SCHEMA_URL,
        "sha256": PORTABLE_SCHEMA_SHA256,
        "bytes": len(schema),
    }
    if lock != expected:
        fail("portable Agent Plugin schema lock does not match its pinned contract")
    if hashlib.sha256(schema).hexdigest() != PORTABLE_SCHEMA_SHA256:
        fail("portable Agent Plugin schema bytes differ from the pinned contract")


def check_rejects_unknown_argument(root: Path) -> None:
    before = snapshot_tree(root)
    result = run_generator(root, [UNKNOWN_ARGUMENT])
    after = snapshot_tree(root)
    if result.returncode == 0:
        fail("unknown generator argument was accepted")
    if after != before:
        fail("unknown generator argument modified the tree")


def apply_silent_repair_mutation(root: Path) -> None:
    path = root / GENERATOR
    text = path.read_text(encoding="utf-8")
    anchor = 'if __name__ == "__main__":\n    main()'
    if text.count(anchor) != 1:
        fail("silent-repair mutation could not find the generator entrypoint")
    path.write_text(
        text.replace(
            anchor,
            'if __name__ == "__main__":\n'
            "    import sys as _sys\n"
            "    _sys.argv = [_sys.argv[0]]\n"
            "    main()",
            1,
        ),
        encoding="utf-8",
    )


def apply_omit_plugin_skill_outputs(root: Path) -> None:
    path = root / GENERATOR
    text = path.read_text(encoding="utf-8")
    anchor = (
        "        *[(output, rendered_plugin_skill.encode(\"ascii\")) "
        "for output in PLUGIN_SKILL_OUTPUTS],\n"
    )
    if text.count(anchor) != 1:
        fail("omission mutation could not find PLUGIN_SKILL_OUTPUTS render line")
    path.write_text(text.replace(anchor, "", 1), encoding="utf-8")


def apply_omit_portable_skill_output(root: Path) -> None:
    path = root / GENERATOR
    text = path.read_text(encoding="utf-8")
    anchor = '        (PORTABLE_SKILL_OUTPUT, rendered_portable_skill.encode("ascii")),\n'
    if text.count(anchor) != 1:
        fail("omission mutation could not find portable skill render line")
    path.write_text(text.replace(anchor, "", 1), encoding="utf-8")


def apply_portable_schema_byte_mutation(root: Path) -> None:
    path = root / PORTABLE_SCHEMA
    path.write_bytes(path.read_bytes() + b"\n")


def expect_pins_reject(name: str, mutate) -> None:
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        mutate(root)
        try:
            check_detects_named_drift_without_writing(root)
        except SystemExit as error:
            if str(error) in {
                "--check accepted drifted golden-path outputs",
                "--check modified the tree it was asked only to compare",
            }:
                return
            raise
        fail(f"{name}: self-test accepted writer-mode --check")


def expect_unknown_pin_rejects(name: str, mutate) -> None:
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        mutate(root)
        try:
            check_rejects_unknown_argument(root)
        except SystemExit as error:
            if str(error) == "unknown generator argument was accepted":
                return
            raise
        fail(f"{name}: self-test accepted an ignored unknown argument")


def expect_omission_rejects(name: str, mutate) -> None:
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        mutate(root)
        try:
            check_detects_named_drift_without_writing(root)
        except SystemExit as error:
            message = str(error)
            if message.startswith("--check did not name drifted path:") or message in {
                "--check accepted drifted golden-path outputs",
                "--check modified the tree it was asked only to compare",
            }:
                return
            raise
        fail(f"{name}: self-test accepted omitted generated output group")


def expect_schema_lock_rejects(name: str, mutate) -> None:
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        mutate(root)
        try:
            check_portable_schema_lock(root)
        except SystemExit as error:
            if "pinned contract" in str(error):
                return
            raise
        fail(f"{name}: self-test accepted modified portable schema bytes")


def main() -> None:
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        check_in_sync_is_clean(root)
        check_portable_schema_lock(root)
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        check_detects_named_drift_without_writing(root)
    with tempfile.TemporaryDirectory() as raw:
        root = Path(raw)
        seed_case(root)
        check_rejects_unknown_argument(root)

    expect_pins_reject("silent-repair --check", apply_silent_repair_mutation)
    expect_unknown_pin_rejects("ignored unknown argument", apply_silent_repair_mutation)
    expect_omission_rejects(
        "omit PLUGIN_SKILL_OUTPUTS", apply_omit_plugin_skill_outputs
    )
    expect_omission_rejects(
        "omit PORTABLE_SKILL_OUTPUT", apply_omit_portable_skill_output
    )
    expect_schema_lock_rejects(
        "portable schema byte drift", apply_portable_schema_byte_mutation
    )
    print("golden-path generator --check: compares bytes, names drift, rejects unknown argv")


if __name__ == "__main__":
    main()
