name: Verdict Gate

on:
  push:
  pull_request:

jobs:
  verdict-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Setup Environment (e.g. Install Verdict)
      # In a real setup, you would download the binary release.
      # For now, we assume building from source or using a pre-installed binary.
      - name: Build Verdict
        run: cargo build --release

      # 2. Run Agent Traces (if available)
      # This step assumes you have an integration test suite that emits OTel traces.
      # Ideally, you run your agent against a mock or replay environment here.
      # For this example, we use the provided fixtures.

      - name: Ingest Traces
        env:
          VERDICT_BIN: ./target/release/verdict
        run: |
          # Example: Ingesting traces for 'web-search-agent'
          $VERDICT_BIN trace ingest-otel \
            --input examples/web-search-agent/otel_trace.jsonl \
            --db .eval/eval.db \
            --suite web-search-suite \
            --out-trace otel.v2.jsonl

      # 3. Run Verdict Gate
      - name: Run Verdict Gate
        env:
          VERDICT_BIN: ./target/release/verdict
        run: |
          $VERDICT_BIN ci \
            --config examples/web-search-agent/eval.yaml \
            --db .eval/eval.db \
            --trace-file otel.v2.jsonl \
            --replay-strict \
            --rerun-failures 0
