version: '2.0'
name: mcp-dev
tools:
  allow:
  - '*'
  deny:
  - exec
  - shell
  - bash
  - cmd
  - powershell
  - spawn
  - python_sandbox
allow: null
deny: null
schemas:
  read_file:
    additionalProperties: true
    properties:
      path:
        minLength: 1
        pattern: ^/app/.*|^/data/.*|^/workspace/.*
        type: string
    required:
    - path
    type: object
constraints: []
enforcement:
  unconstrained_tools: warn
limits: null
signatures:
  check_descriptions: true
